//! AUTO-GENERATED by ori-arch — do not edit.
//! Regenerate via the /ori-arch skill (Claude Code) — see .apm/skills/ori-arch/SKILL.md
//! Source: .ori/architecture.md (root id: "__ORI_ROOT_ID__")

use std::fs;
use std::path::{Path, PathBuf};

const ROOT_PATH: &str = "__ORI_ROOT_PATH__";
const SLICE_BASE: &str = "__ORI_SLICE_BASE__";
const PUBLIC_ENTRY: &str = "__ORI_PUBLIC_ENTRY__";
const CROSS_SLICE_PROHIBITED: bool = __ORI_CROSS_SLICE_PROHIBITED__;

struct LayerMatcher {
    layer_id: &'static str,
    kind: &'static str,
    prefix: &'static str,
    slice: bool,
}

const MATCHERS: &[LayerMatcher] = &[__ORI_MATCHERS__];

const CROSS_LAYER_RULES: &[(&str, &[&str])] = &[__ORI_CROSS_LAYER_RULES__];

#[derive(Debug, Clone)]
struct LayerHit {
    layer_id: &'static str,
    kind: &'static str,
    slice_name: Option<String>,
}

fn classify(rel: &str) -> Option<LayerHit> {
    for m in MATCHERS {
        if rel.starts_with(m.prefix) {
            if m.slice {
                let tail = &rel[m.prefix.len()..];
                let mut segs = tail.split('/').filter(|s| !s.is_empty());
                let first = segs.next()?;
                segs.next()?; // require at least one segment inside the slice folder
                return Some(LayerHit {
                    layer_id: m.layer_id,
                    kind: m.kind,
                    slice_name: Some(first.to_string()),
                });
            }
            return Some(LayerHit {
                layer_id: m.layer_id,
                kind: m.kind,
                slice_name: None,
            });
        }
    }
    None
}

fn walk_rust(dir: &Path, out: &mut Vec<PathBuf>) {
    let entries = match fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return,
    };
    for entry in entries.flatten() {
        let name = entry.file_name();
        let name = name.to_string_lossy();
        if name.starts_with('.') || name == "target" || name == "node_modules" {
            continue;
        }
        let path = entry.path();
        if path.is_dir() {
            walk_rust(&path, out);
        } else if path.extension().and_then(|e| e.to_str()) == Some("rs") {
            out.push(path);
        }
    }
}

fn extract_uses(content: &str) -> Vec<(String, usize)> {
    let mut out = Vec::new();
    for (i, line) in content.lines().enumerate() {
        let trimmed = line.trim_start();
        let rest = trimmed
            .strip_prefix("pub use ")
            .or_else(|| trimmed.strip_prefix("use "));
        if let Some(rest) = rest {
            let end = rest
                .find(|c: char| c == ';' || c == '{' || c == ' ')
                .unwrap_or(rest.len());
            let head = rest[..end].trim().trim_end_matches("::");
            if !head.is_empty() {
                out.push((head.to_string(), i + 1));
            }
        }
    }
    out
}

fn module_dir(importer: &Path) -> Option<PathBuf> {
    // Rust 2018+ module-file rule:
    //   <dir>/mod.rs        defines module <dir>
    //   <dir>/<name>.rs     defines module <name> nested under <dir>
    // The directory of the *importer module* is therefore:
    //   for mod.rs           → importer.parent()        (current dir IS the module dir)
    //   for any other file   → importer.parent().join(<name>)  conceptually,
    //                          but its file siblings live in importer.parent() itself.
    // We return the dir that holds sibling files reachable via self::*.
    let parent = importer.parent()?;
    if importer.file_name().and_then(|s| s.to_str()) == Some("mod.rs") {
        Some(parent.to_path_buf())
    } else {
        Some(parent.to_path_buf())
    }
}

fn parent_module_dir(importer: &Path) -> Option<PathBuf> {
    // The dir reached by super::* — one module up from the importer.
    //   for <dir>/mod.rs     → <dir>'s parent
    //   for <dir>/<name>.rs  → <dir> itself (because <name>'s parent module is <dir>)
    let parent = importer.parent()?;
    if importer.file_name().and_then(|s| s.to_str()) == Some("mod.rs") {
        parent.parent().map(Path::to_path_buf)
    } else {
        Some(parent.to_path_buf())
    }
}

fn resolve_use(target: &str, importer: &Path) -> Option<PathBuf> {
    if let Some(rest) = target.strip_prefix("crate::") {
        let mut p = PathBuf::from(ROOT_PATH);
        for s in rest.split("::").filter(|s| !s.is_empty()) {
            p.push(s);
        }
        p.set_extension("rs");
        return Some(p);
    }
    if let Some(rest) = target.strip_prefix("super::") {
        let mut p = parent_module_dir(importer)?;
        for s in rest.split("::").filter(|s| !s.is_empty()) {
            p.push(s);
        }
        p.set_extension("rs");
        return Some(p);
    }
    if let Some(rest) = target.strip_prefix("self::") {
        let mut p = module_dir(importer)?;
        for s in rest.split("::").filter(|s| !s.is_empty()) {
            p.push(s);
        }
        p.set_extension("rs");
        return Some(p);
    }
    None
}

fn check_pair(importer: &LayerHit, target: &LayerHit) -> Result<(), String> {
    if importer.layer_id == target.layer_id
        && importer.kind == "slice"
        && importer.slice_name.is_some()
        && importer.slice_name == target.slice_name
    {
        return Ok(()); // same slice — governed by slice_internal (not enforced here)
    }

    if CROSS_SLICE_PROHIBITED
        && importer.layer_id == target.layer_id
        && importer.kind == "slice"
        && importer.slice_name != target.slice_name
    {
        return Err(format!(
            "cross-slice direct import: {} → {}",
            importer.slice_name.as_deref().unwrap_or("?"),
            target.slice_name.as_deref().unwrap_or("?"),
        ));
    }

    for (from, allow) in CROSS_LAYER_RULES {
        if *from == importer.layer_id {
            if allow.contains(&target.layer_id) {
                return Ok(());
            }
            return Err(format!(
                "cross-layer: {} → {} not in allow-list [{}]",
                importer.layer_id,
                target.layer_id,
                allow.join(", "),
            ));
        }
    }
    Err(format!("no cross_layer rule for from=\"{}\"", importer.layer_id))
}

#[test]
fn architecture_rules() {
    eprintln!("ori arch: scanning {} (public_entry={})", ROOT_PATH, PUBLIC_ENTRY);
    eprintln!("ori arch: slice_base={}", SLICE_BASE);

    let mut files = Vec::new();
    walk_rust(Path::new(ROOT_PATH), &mut files);

    let mut violations: Vec<String> = Vec::new();
    for file in &files {
        let rel = file.to_string_lossy().replace('\\', "/");
        let importer = match classify(&rel) {
            Some(h) => h,
            None => continue,
        };
        let content = match fs::read_to_string(file) {
            Ok(c) => c,
            Err(_) => continue,
        };
        for (target, line) in extract_uses(&content) {
            let resolved = match resolve_use(&target, file) {
                Some(r) => r,
                None => continue,
            };
            let rel_target = resolved.to_string_lossy().replace('\\', "/");
            let target_hit = match classify(&rel_target) {
                Some(h) => h,
                None => continue,
            };
            if let Err(reason) = check_pair(&importer, &target_hit) {
                violations.push(format!(
                    "{}:{}: use {} ({}): {}",
                    rel,
                    line,
                    target,
                    target_hit.layer_id,
                    reason,
                ));
            }
        }
    }

    if !violations.is_empty() {
        panic!(
            "ori arch: {} violation(s):\n  {}\n",
            violations.len(),
            violations.join("\n  "),
        );
    }
}
