// AUTO-GENERATED by ori-architect — do not edit.
// Regenerate via the /ori-architect skill (Claude Code) — see .apm/skills/ori-architect/SKILL.md
// Source: .ori/architecture.md
//
// Usage: extend your eslint.config.js by spreading this array:
//   import oriArch from "./eslint.config.ori.js";
//   export default [...oriArch, /* your rules */];

import boundaries from "eslint-plugin-boundaries";

export default [
  {
    files: ["__ORI_FILE_PATTERN__"],
    plugins: { boundaries },
    settings: {
      "boundaries/elements": __ORI_ELEMENTS__,
    },
    rules: {
      "boundaries/dependencies": [
        "error",
        {
          default: "disallow",
          rules: __ORI_RULES__,
        },
      ],
      "boundaries/no-private": ["error", { allowUncles: true }],
      "boundaries/no-unknown": "off",
    },
  },
  ...__ORI_EXTRA_BLOCKS__,
];
