// AUTO-REGENERATED by tauri-specta at `pnpm tauri dev|build` time from the
// Rust commands declared in src-tauri/src/features/*/commands.rs. The file
// committed here is a hand-written placeholder that mirrors the expected
// shape so that `pnpm typecheck` succeeds before the first Rust build.
//
// Cross-root contract:
//   from: src-tauri/src/features/*/commands (Rust)
//   to:   src/lib/shared/ipc (TypeScript)
//   generator: tauri-specta
//
// Do NOT hand-edit after the first `pnpm tauri dev` — the build step will
// overwrite this file with bindings generated from the live Rust signatures.

export interface CompleteTaskInput {
  readonly id: string;
}

export interface CompleteTaskResult {
  readonly id: string;
  readonly completed: boolean;
}

// Minimal invoke shim. Replace with the tauri-specta-generated function once
// `pnpm tauri dev` has been run at least once in this project.
export async function completeTaskCmd(_input: CompleteTaskInput): Promise<CompleteTaskResult> {
  throw new Error(
    "completeTaskCmd: tauri-specta bindings have not been generated yet. Run `pnpm tauri dev` once to overwrite src/lib/shared/ipc/bindings.ts.",
  );
}
