// AUTO-REGENERATED by tauri-specta at `pnpm tauri dev|build` time from the
// Rust commands declared in src-tauri/src/features/*/commands.rs. The file
// committed here is a hand-written placeholder that mirrors the expected
// shape so that `pnpm typecheck` succeeds before the first Rust build, AND
// so that Slice DoD boundary tests (see ../../slices/<slice>/tests/dod.test.ts)
// can route through @tauri-apps/api/mocks#mockIPC.
//
// Cross-root contract:
//   from: src-tauri/src/features/*/commands (Rust)
//   to:   src/lib/shared/ipc (TypeScript)
//   generator: tauri-specta
//
// Do NOT hand-edit after the first `pnpm tauri dev` — the build step will
// overwrite this file with bindings generated from the live Rust signatures.

import { invoke } from "@tauri-apps/api/core";

export interface CompleteTaskInput {
  readonly id: string;
}

export interface CompleteTaskResult {
  readonly id: string;
  readonly completed: boolean;
}

// tauri-specta-style `commands` namespace. Each method is a thin wrapper
// around `invoke("<rust_command_name>", args)` so that boundary tests can
// substitute the IPC layer via `mockIPC(...)` without touching the call site.
//
// Slice DoD rule 2 (.apm/skills/ori-arch/patterns/ddd-vsa-hex/pattern.md):
// boundary tests MUST go through this object — direct `application/*`
// imports from the test file are a DoD violation.
export const commands = {
  async completeTaskCmd(input: CompleteTaskInput): Promise<CompleteTaskResult> {
    return await invoke<CompleteTaskResult>("complete_task_cmd", { id: input.id });
  },
};

// Legacy top-level alias retained for callers that import the flat symbol.
// Prefer `commands.completeTaskCmd` going forward.
export async function completeTaskCmd(input: CompleteTaskInput): Promise<CompleteTaskResult> {
  return commands.completeTaskCmd(input);
}
