#!/usr/bin/env bash
# ori-init: install Tauri / specta scaffold into a freshly `pnpm tauri init`-ed app.
#
# Called by /ori-arch after the upstream framework init for stack=typescript-tauri
# completes (apps/<app>/src-tauri/ exists). Implements the specta infra side of
# Slice DoD enforcement (rules 2–4 in
# .apm/skills/ori-arch/patterns/ddd-vsa-hex/pattern.md):
#
#   - src-tauri/Cargo.toml      : tauri-specta + specta + specta-typescript deps
#   - src-tauri/src/bin/export-types.rs : specta bindings export entry
#   - apm-scripts/specta-build.sh : phase_hooks 経由で呼ばれる build script
#   - src/<BC>/shared/test-fixtures/setupProductionBuilder.ts : production wiring 雛形
#   - src/<BC>/shared/ipc/.gitkeep : bindings 出力先 dir (bindings.ts は初回 build で生成)
#
# Usage:
#   install-tauri-scaffold.sh --dest <repo-root> --app-name <app> --bc-name <bc-kebab> [--force]
#
# Exit codes:
#   0  success (or no-op if scaffold already present and --force not given)
#   1  IO / cargo error
#   2  usage error
set -euo pipefail

FORCE=false
DEST=""
APP_NAME=""
BC_NAME=""

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TPL_DIR="$SCRIPT_DIR/templates/tauri-stack"

usage() {
  cat >&2 <<'EOF'
Usage: install-tauri-scaffold.sh [options]

Required:
  --dest <dir>        Repo root containing apps/<app-name>/src-tauri/
  --app-name <name>   Tauri app name (must match apps/<app-name>/)
  --bc-name <name>    Bounded context name in kebab-case (TS-side BC dir name)

Optional:
  --force             Overwrite existing scaffold files
  -h, --help          Show this help and exit
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --force)     FORCE=true; shift ;;
    --dest)      DEST="${2:-}"; shift 2 ;;
    --app-name)  APP_NAME="${2:-}"; shift 2 ;;
    --bc-name)   BC_NAME="${2:-}"; shift 2 ;;
    -h|--help)   usage; exit 0 ;;
    *) echo "ERROR: unknown argument: $1" >&2; usage; exit 2 ;;
  esac
done

[[ -z "$DEST" || -z "$APP_NAME" || -z "$BC_NAME" ]] && { usage; exit 2; }

# kebab → snake for Rust identifier rules (mirrors render-architecture.js).
BC_NAME_RS="${BC_NAME//-/_}"
APP_NAME_RS="${APP_NAME//-/_}"

APP_DIR="$DEST/apps/$APP_NAME"
ST_DIR="$APP_DIR/src-tauri"
TS_BC_DIR="$APP_DIR/src/$BC_NAME"

if [[ ! -d "$ST_DIR" ]]; then
  echo "ERROR: $ST_DIR not found — run 'pnpm tauri init' inside $APP_DIR first." >&2
  exit 2
fi
if [[ ! -d "$APP_DIR/src" ]]; then
  echo "ERROR: $APP_DIR/src not found — run upstream framework init first." >&2
  exit 2
fi
if [[ ! -d "$TPL_DIR" ]]; then
  echo "ERROR: scaffold templates missing under $TPL_DIR" >&2
  exit 1
fi

# Substitute __APP_NAME__ / __APP_NAME_RS__ / __BC_NAME__ / __BC_NAME_RS__ in a
# template file. All values are constrained to [a-z0-9_-] by upstream
# validation so no sed metachar escaping is needed.
render_tpl() {
  local src="$1" dest="$2"
  if [[ -e "$dest" && "$FORCE" != true ]]; then
    echo "SKIP: $dest already exists (use --force to overwrite)"
    return 0
  fi
  mkdir -p "$(dirname "$dest")"
  sed -e "s/__APP_NAME__/$APP_NAME/g" \
      -e "s/__APP_NAME_RS__/$APP_NAME_RS/g" \
      -e "s/__BC_NAME__/$BC_NAME/g" \
      -e "s/__BC_NAME_RS__/$BC_NAME_RS/g" \
      "$src" > "$dest"
  echo "OK: wrote $dest"
}

copy_file() {
  local src="$1" dest="$2" mode="${3:-}"
  if [[ -e "$dest" && "$FORCE" != true ]]; then
    echo "SKIP: $dest already exists (use --force to overwrite)"
    return 0
  fi
  mkdir -p "$(dirname "$dest")"
  cp "$src" "$dest"
  [[ -n "$mode" ]] && chmod "$mode" "$dest"
  echo "OK: wrote $dest"
}

# 1. specta export entry (Rust)
render_tpl \
  "$TPL_DIR/src-tauri/src/bin/export-types.rs.tpl" \
  "$ST_DIR/src/bin/export-types.rs"

# 2. specta-build.sh (phase hook entry)
copy_file \
  "$TPL_DIR/apm-scripts/specta-build.sh" \
  "$DEST/apm-scripts/specta-build.sh" \
  755

# 3. test fixture skeleton (production wiring helper)
render_tpl \
  "$TPL_DIR/bc-shared/test-fixtures/setupProductionBuilder.ts.tpl" \
  "$TS_BC_DIR/shared/test-fixtures/setupProductionBuilder.ts"

# 4. bindings/ dir placeholder (bindings.ts is generated by specta)
copy_file \
  "$TPL_DIR/bc-shared/ipc/.gitkeep" \
  "$TS_BC_DIR/shared/ipc/.gitkeep"

# 5. Cargo.toml deps. cargo add is preferred (it places deps in the right
# table, resolves versions, and is idempotent on existing entries). If
# cargo is missing or `tauri/specta` feature wiring is non-trivial,
# emit a hand-merge fallback so the operator can finish manually.
add_cargo_deps() {
  if ! command -v cargo >/dev/null 2>&1; then
    cat >&2 <<EOF
NOTE: cargo not on PATH — append the following to $ST_DIR/Cargo.toml manually:

  [dependencies]
  tauri        = { version = "2", features = ["specta"] }
  specta       = { version = "2.0.0-rc", features = ["derive"] }
  tauri-specta = { version = "2.0.0-rc", features = ["javascript", "typescript"] }
  specta-typescript = "0.0.7"
EOF
    return 0
  fi
  echo "Running: cargo add tauri-specta specta specta-typescript  (in $ST_DIR)"
  ( cd "$ST_DIR" && \
    cargo add tauri-specta --features javascript,typescript >/dev/null && \
    cargo add specta --features derive >/dev/null && \
    cargo add specta-typescript >/dev/null \
  ) || {
    echo "WARN: cargo add failed; merge the deps block above into $ST_DIR/Cargo.toml manually." >&2
    return 0
  }
  # tauri 自体は pnpm tauri init で既に entry がある想定。`specta` feature を
  # 付け足したいので、cargo add 越しに features を明示。
  ( cd "$ST_DIR" && cargo add tauri --features specta >/dev/null ) || true
}
add_cargo_deps

echo
echo "specta scaffold installed under apps/$APP_NAME/. Next:"
echo "  - Add the first slice via /ori-flow new-slice <slice-id>"
echo "  - Rerun bindings export with: bash apm-scripts/specta-build.sh --app-dir apps/$APP_NAME"
